In [1]:
import numpy as np
import pandas as pd

In [2]:
anime = pd.read_csv('anime.csv')
anime_overview = pd.read_csv('anime_with_synopsis.csv')
anime_images = pd.read_csv('images.csv')

In [3]:
anime_images

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,background,premiered,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Inu x Boku SS was licensed by Sentai Filmworks...,Winter 2012,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ..."
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,NaN,Spring 2007,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi..."
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,NaN,Fall 2008,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ..."
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Princess Tutu aired in two parts. The first pa...,Summer 2002,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ..."
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,NaN,Fall 2012,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14473,26089,Gutchonpa Omoshiro Hanashi,NaN,グッチョンパおもしろ話,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Unknown,5,Finished Airing,...,NaN,Fall 1987,Unknown,"{'Other': [{'mal_id': 26087, 'type': 'anime', ...",NaN,NaN,NaN,Kids,[],[]
14474,21525,Geba Geba Shou Time!,NaN,ゲバゲバ笑タイム!,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Unknown,1,Finished Airing,...,NaN,NaN,NaN,[],Studio Lotus,NaN,NaN,Comedy,[],[]
14475,37897,Godzilla: Hoshi wo Kuu Mono,NaN,GODZILLA -星を喰う者-,"Godzilla Part 3, Godzilla: Eater of Stars",https://myanimelist.cdn-dena.com/images/anime/...,Movie,Other,1,Not yet aired,...,NaN,NaN,NaN,"{'Prequel': [{'mal_id': 36816, 'type': 'anime'...",NaN,NaN,NaN,"Action, Sci-Fi, Adventure, Fantasy",[],[]
14476,34193,Nippon Mukashibanashi: Sannen Netarou,NaN,日本昔ばなし 三ねん寝太郎,NaN,https://myanimelist.cdn-dena.com/images/anime/...,OVA,Other,1,Finished Airing,...,NaN,NaN,NaN,[],NaN,NaN,NaN,"Fantasy, Kids",[],[]
14477,37908,Senjou no Valkyria Special,NaN,戦場のヴァルキュリア Valkyria Chronicles,Senjou no Valkyria Fake Movie Promo,https://myanimelist.cdn-dena.com/images/anime/...,Special,Unknown,1,Finished Airing,...,NaN,NaN,NaN,"{'Other': [{'mal_id': 5507, 'type': 'anime', '...",NaN,NaN,A-1 Pictures,Comedy,[],[]

In [4]:
anime_images.rename(columns = {'anime_id':'MAL_ID'}, inplace = True)

In [5]:
anime.head(5)

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0

In [6]:
anime_overview.head(5)

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...

In [7]:
anime.describe()

,MAL_ID,Popularity,Members,Favorites,Watching,Completed,On-Hold,Dropped,Plan to Watch
count,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,1.756200e+04,17562.000000,17562.000000,17562.000000
mean,21477.192347,8763.452340,3.465854e+04,457.746270,2231.487758,2.209557e+04,955.049653,1176.599533,8199.831227
std,14900.093170,5059.327278,1.252821e+05,4063.473313,14046.688133,9.100919e+04,4275.675096,4740.348653,23777.691963
min,1.000000,0.000000,1.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.000000
25%,5953.500000,4383.500000,3.360000e+02,0.000000,13.000000,1.110000e+02,6.000000,37.000000,112.000000
50%,22820.000000,8762.500000,2.065000e+03,3.000000,73.000000,8.175000e+02,45.000000,77.000000,752.500000
75%,35624.750000,13145.000000,1.322325e+04,31.000000,522.000000,6.478000e+03,291.750000,271.000000,4135.500000
max,48492.000000,17565.000000,2.589552e+06,183914.000000,887333.000000,2.182587e+06,187919.000000,174710.000000,425531.000000

In [8]:
anime_overview.describe()

             MAL_ID
count  16214.000000
mean   22069.271555
std    14849.798248
min        1.000000
25%     6728.500000
50%    24164.000000
75%    35978.750000
max    48492.000000

In [9]:
anime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17562 entries, 0 to 17561
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MAL_ID         17562 non-null  int64
 1   Name           17562 non-null  object
 2   Score          17562 non-null  object
 3   Genres         17562 non-null  object
 4   English name   17562 non-null  object
 5   Japanese name  17562 non-null  object
 6   Type           17562 non-null  object
 7   Episodes       17562 non-null  object
 8   Aired          17562 non-null  object
 9   Premiered      17562 non-null  object
 10  Producers      17562 non-null  object
 11  Licensors      17562 non-null  object
 12  Studios        17562 non-null  object
 13  Source         17562 non-null  object
 14  Duration       17562 non-null  object
 15  Rating         17562 non-null  object
 16  Ranked         17562 non-null  object
 17  Popularity     17562 non-null  int64
 18  Members        17562 non-null  int64
 19  Favorites      17562 non-null  int64
 20  Watching       17562 non-null  int64
 21  Completed      17562 non-null  int64
 22  On-Hold        17562 non-null  int64
 23  Dropped        17562 non-null  int64
 24  Plan to Watch  17562 non-null  int64
 25  Score-10       17562 non-null  object
 26  Score-9        17562 non-null  object
 27  Score-8        17562 non-null  object
 28  Score-7        17562 non-null  object
 29  Score-6        17562 non-null  object
 30  Score-5        17562 non-null  object
 31  Score-4        17562 non-null  object
 32  Score-3        17562 non-null  object
 33  Score-2        17562 non-null  object
 34  Score-1        17562 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.7+ MB

In [10]:
#id
#name
#genres
#type
#studios
#overview
#rating

data = anime[['MAL_ID','Name','Genres','Type']]

In [11]:
data = data.merge(anime_overview[['MAL_ID','sypnopsis']])

In [12]:
data

,MAL_ID,Name,Genres,Type,sypnopsis
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,"In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,"other day, another bounty—such is the life of ..."
2,6,Trigun,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",TV,"Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,"Action, Mystery, Police, Supernatural, Drama, ...",TV,ches are individuals with special powers like ...
4,8,Bouken Ou Beet,"Adventure, Fantasy, Shounen, Supernatural",TV,It is the dark century and the people are suff...
...,...,...,...,...,...
16209,48481,Daomu Biji Zhi Qinling Shen Shu,"Adventure, Mystery, Supernatural",ONA,No synopsis information has been added to this...
16210,48483,Mieruko-chan,"Comedy, Horror, Supernatural",TV,ko is a typical high school student whose life...
16211,48488,Higurashi no Naku Koro ni Sotsu,"Mystery, Dementia, Horror, Psychological, Supe...",TV,Sequel to Higurashi no Naku Koro ni Gou .
16212,48491,Yama no Susume: Next Summit,"Adventure, Slice of Life, Comedy",TV,New Yama no Susume anime.
16213,48492,Scarlet Nexus,"Action, Fantasy",TV,Solar calendar year 2020: grotesque organisms ...

In [13]:
data = data[~data['sypnopsis'].isnull()]

In [14]:
data[data['Type'] == 'Unknown'].count()

MAL_ID       37
Name         37
Genres       37
Type         37
sypnopsis    37
dtype: int64

In [15]:
data = data[data['Type'] != 'Unknown']

In [16]:
data[data['Genres'] == 'Unknown'].count()

MAL_ID       62
Name         62
Genres       62
Type         62
sypnopsis    62
dtype: int64

In [17]:
data = data[data['Genres'] != 'Unknown']

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16107 entries, 0 to 16213
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MAL_ID     16107 non-null  int64
 1   Name       16107 non-null  object
 2   Genres     16107 non-null  object
 3   Type       16107 non-null  object
 4   sypnopsis  16107 non-null  object
dtypes: int64(1), object(4)
memory usage: 755.0+ KB

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16107 entries, 0 to 16213
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MAL_ID     16107 non-null  int64
 1   Name       16107 non-null  object
 2   Genres     16107 non-null  object
 3   Type       16107 non-null  object
 4   sypnopsis  16107 non-null  object
dtypes: int64(1), object(4)
memory usage: 755.0+ KB

In [20]:
data.iloc[0]

MAL_ID                                                       1
Name                                              Cowboy Bebop
Genres         Action, Adventure, Comedy, Drama, Sci-Fi, Space
Type                                                        TV
sypnopsis    In the year 2071, humanity has colonized sever...
Name: 0, dtype: object

In [21]:
data['Genres'] = data['Genres'].apply(lambda x:x.split(','))

In [22]:
data['sypnopsis'] = data['sypnopsis'].apply(lambda x:x.split())

In [23]:
data

,MAL_ID,Name,Genres,Type,sypnopsis
0,1,Cowboy Bebop,"[Action, Adventure, Comedy, Drama, Sci-Fi,...",TV,"[In, the, year, 2071,, humanity, has, colonize..."
1,5,Cowboy Bebop: Tengoku no Tobira,"[Action, Drama, Mystery, Sci-Fi, Space]",Movie,"[other, day,, another, bounty—such, is, the, l..."
2,6,Trigun,"[Action, Sci-Fi, Adventure, Comedy, Drama,...",TV,"[Vash, the, Stampede, is, the, man, with, a, $..."
3,7,Witch Hunter Robin,"[Action, Mystery, Police, Supernatural, Dr...",TV,"[ches, are, individuals, with, special, powers..."
4,8,Bouken Ou Beet,"[Adventure, Fantasy, Shounen, Supernatural]",TV,"[It, is, the, dark, century, and, the, people,..."
...,...,...,...,...,...
16209,48481,Daomu Biji Zhi Qinling Shen Shu,"[Adventure, Mystery, Supernatural]",ONA,"[No, synopsis, information, has, been, added, ..."
16210,48483,Mieruko-chan,"[Comedy, Horror, Supernatural]",TV,"[ko, is, a, typical, high, school, student, wh..."
16211,48488,Higurashi no Naku Koro ni Sotsu,"[Mystery, Dementia, Horror, Psychological, ...",TV,"[Sequel, to, Higurashi, no, Naku, Koro, ni, Go..."
16212,48491,Yama no Susume: Next Summit,"[Adventure, Slice of Life, Comedy]",TV,"[New, Yama, no, Susume, anime.]"
16213,48492,Scarlet Nexus,"[Action, Fantasy]",TV,"[Solar, calendar, year, 2020:, grotesque, orga..."

In [24]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [25]:
data['Genres'] = data['Genres'].apply(collapse)
data['Type'] = data['Type'].apply(collapse)

In [26]:
data['tags'] = data['Genres'] + data['Type'] + data['sypnopsis']

In [27]:
new =  data.drop(columns=['Genres','Type','sypnopsis'])

In [28]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,MAL_ID,Name,tags
0,1,Cowboy Bebop,Action Adventure Comedy Drama Sci-Fi Space T V...
1,5,Cowboy Bebop: Tengoku no Tobira,Action Drama Mystery Sci-Fi Space M o v i e ot...
2,6,Trigun,Action Sci-Fi Adventure Comedy Drama Shounen T...
3,7,Witch Hunter Robin,Action Mystery Police Supernatural Drama Magic...
4,8,Bouken Ou Beet,Adventure Fantasy Shounen Supernatural T V It ...

In [29]:
new['tags'] = new['tags'].apply(lambda x: x.lower())
new.head()

,MAL_ID,Name,tags
0,1,Cowboy Bebop,action adventure comedy drama sci-fi space t v...
1,5,Cowboy Bebop: Tengoku no Tobira,action drama mystery sci-fi space m o v i e ot...
2,6,Trigun,action sci-fi adventure comedy drama shounen t...
3,7,Witch Hunter Robin,action mystery police supernatural drama magic...
4,8,Bouken Ou Beet,adventure fantasy shounen supernatural t v it ...

In [30]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [31]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [32]:
new_df = new
new_df['tags'] = new['tags'].apply(stem)
new_df

,MAL_ID,Name,tags
0,1,Cowboy Bebop,action adventur comedi drama sci-fi space t v ...
1,5,Cowboy Bebop: Tengoku no Tobira,action drama mysteri sci-fi space m o v i e ot...
2,6,Trigun,action sci-fi adventur comedi drama shounen t ...
3,7,Witch Hunter Robin,action mysteri polic supernatur drama magic t ...
4,8,Bouken Ou Beet,adventur fantasi shounen supernatur t v it is ...
...,...,...,...
16209,48481,Daomu Biji Zhi Qinling Shen Shu,adventur mysteri supernatur o n a no synopsi i...
16210,48483,Mieruko-chan,comedi horror supernatur t v ko is a typic hig...
16211,48488,Higurashi no Naku Koro ni Sotsu,mysteri dementia horror psycholog supernatur t...
16212,48491,Yama no Susume: Next Summit,adventur sliceoflif comedi t v new yama no sus...
16213,48492,Scarlet Nexus,action fantasi t v solar calendar year 2020: g...

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [34]:
vector = cv.fit_transform(new_df['tags']).toarray()
vector.shape

(16107, 5000)

In [35]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 3, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
cv.get_feature_names()

['00',
 '000',
 '01',
 '10',
 '100',
 '10th',
 '11',
 '11th',
 '12',
 '12th',
 '13',
 '13th',
 '14',
 '14th',
 '15',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1945',
 '1980',
 '1983',
 '1989',
 '1998',
 '1999',
 '19th',
 '1st',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '20th',
 '21',
 '21st',
 '22',
 '22nd',
 '23',
 '24',
 '25',
 '25th',
 '26',
 '27',
 '28',
 '29',
 '2d',
 '2nd',
 '30',
 '300',
 '30th',
 '31',
 '3d',
 '3rd',
 '4th',
 '50',
 '500',
 '5th',
 '60',
 '6th',
 '70',
 '7th',
 '80',
 '8th',
 '90',
 '999',
 '9th',
 'abandon',
 'abduct',
 'abe',
 'abil',
 'abilities',
 'ability',
 'abl',
 'abnorm',
 'aboard',
 'abov',
 'abroad',
 'abruptli',
 'absent',
 'absolut',
 'absorb',
 'abstract',
 'absurd',
 'abus',
 'abyss',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'accord',
 'account',
 'accus',
 'accustom',
 'ace',
 'achiev',
 'acknowledg',
 'acquaint',
 'acquir',
 'act',
 'action',
 'actions',
 'activ',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adapt',
 'add',
 'addit',
 'addition',
 'address',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adult',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'adversari',
 'advertis',
 'advic',
 'advisor',
 'affair',
 'affect',
 'affection',
 'affic',
 'afford',
 'afraid',
 'afro',
 'aftermath',
 'afternoon',
 'afterward',
 'ag',
 'age',
 'agenc',
 'agency',
 'agent',
 'aggress',
 'ago',
 'agre',
 'agricultur',
 'ahead',
 'ai',
 'aichi',
 'aid',
 'aihara',
 'aika',
 'aiko',
 'aim',
 'air',
 'aircraft',
 'airship',
 'aka',
 'akan',
 'akane',
 'akari',
 'akatsuki',
 'akechi',
 'aki',
 'akihabara',
 'akihiko',
 'akihito',
 'akiko',
 'akira',
 'akito',
 'akko',
 'ako',
 'akuma',
 'al',
 'alarm',
 'albeit',
 'album',
 'alchemist',
 'alcohol',
 'alic',
 'alice',
 'alien',
 'aliens',
 'alike',
 'aliv',
 'alive',
 'alley',
 'alli',
 'allianc',
 'alliance',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'amano',
 'amateur',
 'amaz',
 'amazon',
 'ambit',
 'ambiti',
 'ambush',
 'ame',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amon',
 'amuro',
 'amus',
 'ancestor',
 'ancient',
 'android',
 'angel',
 'angels',
 'anger',
 'angri',
 'ani',
 'anidb',
 'anim',
 'animal',
 'animals',
 'animated',
 'animation',
 'anime',
 'animenfo',
 'ann',
 'anna',
 'annihil',
 'anniversari',
 'anniversary',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anoth',
 'anpanman',
 'answer',
 'antholog',
 'anthropomorph',
 'anti',
 'antic',
 'anticip',
 'antics',
 'anymore',
 'anyon',
 'anyth',
 'ao',
 'aoba',
 'aoi',
 'aoki',
 'aoyama',
 'apart',
 'apartment',
 'apocalypt',
 'app',
 'appar',
 'appeal',
 'appear',
 'appearance',
 'appeared',
 'appears',
 'appl',
 'appli',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'ar',
 'araragi',
 'arashi',
 'arata',
 'arc',
 'arcad',
 'area',
 'aren',
 'arena',
 'argument',
 'ari',
 'aria',
 'arima',
 'aris',
 'aristocrat',
 'ark',
 'arm',
 'armi',
 'armor',
 'arms',
 'army',
 'arrang',
 'arrest',
 'arriv',
 'arrival',
 'arrive',
 'arrives',
 'arrog',
 'arrow',
 'arslan',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artist',
 'arts',
 'artwork',
 'asahi',
 'asami',
 'ascend',
 'ash',
 'asia',
 'asian',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'association',
 'assort',
 'assum',
 'asteroid',
 'astro',
 'astronaut',
 'asuka',
 'asuna',
 'ataru',
 'athena',
 'athlet',
 'atmospher',
 'atmosphere',
 'atom',
 'atsuko',
 'atsushi',
 'attach',
 'attack',
 'attacked',
 'attacks',
 'attain',
 'attempt',
 'attend',
 'attent',
 'attention',
 'attitud',
 'attract',
 'audienc',
 'audience',
 'audio',
 'audit',
 'august',
 'aunt',
 'aura',
 'aurora',
 'author',
 'autobot',
 'autumn',
 'avail',
 'avatar',
 'aveng',
 'averag',
 'avex',
 'avoid',
 'await',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'axi',
 'aya',
 'ayaka',
 'ayakashi',
 'ayano',
 'ayas',
 'ayu',
 'ayumi',
 'ayumu',
 'azuma',
 'azusa',
 'babel',
 'babi',
 'baby',
 'background',
 'backkom',
 'bad',
 'bag',
 'bai',
 'baikinman',
 'baka',
 'baki',
 'bakugan',
 'balanc',
 'balance',
 'ball',
 'balloon',
 'bamboo',
 'ban',
 'band',
 'bandai',
 'bandit',
 'bandits',
 'bang',
 'banish',
 'bank',
 'bao',
 'bar',
 'bare',
 'bargain',
 'baron',
 'barren',
 'barrier',
 'bas',
 'basara',
 'base',
 'basebal',
 'baseball',
 'basement',
 'basic',
 'basket',
 'basketbal',
 'basketball',
 'bat',
 'bath',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'battles',
 'battleship',
 'bay',
 'bd',
 'beach',
 'bear',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'bed',
 'bee',
 'beetl',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'beginning',
 'begins',
 'begun',
 'behavior',
 'beings',
 'belief',
 'believ',
 'bell',
 'belong',
 'belov',
 'belt',
 'beneath',
 'benefit',
 'bent',
 'besid',
 'best',
 'bestow',
 'bet',
 'betray',
 'better',
 'beyblad',
 'bicycl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'billion',
 'bind',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blade',
 'blame',
 'blast',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blown',
 'blu',
 'blue',
 'bo',
 'board',
 'boat',
 'bodi',
 'bodies',
 'body',
 'bodyguard',
 'boister',
 'boku',
 'bomb',
 'bond',
 'bone',
 'bonu',
 'book',
 'books',
 'border',
 'bore',
 'born',
 'boss',
 'bottl',
 'bouken',
 'bound',
 'boundari',
 'bounti',
 'bow',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'brain',
 'branch',
 'brand',
 'brave',
 'bread',
 'break',
 'breath',
 'brew',
 'briar',
 'bride',
 'bridg',
 'brief',
 'brigad',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britannia',
 'british',
 'broadcast',
 'broke',
 'broken',
 'brother',
 'brothers',
 'brought',
 'brown',
 'brutal',
 'bu',
 'bubbl',
 'bud',
 'buddha',
 'buddhist',
 'buddi',
 'bug',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bullying',
 'bump',
 'bunch',
 'bundl',
 'bunni',
 'burden',
 'bureau',
 'buri',
 'burn',
 'burst',
 'busi',
 'business',
 'businessman',
 'buster',
 'bustl',
 'butler',
 'butt',
 'butterfli',
 'button',
 'buy',
 'cafe',
 'café',
 'cake',
 'cal',
 'calam',
 'calm',
 'came',
 'camera',
 'camp',
 'campaign',
 'campu',
 'cancel',
 'candi',
 'candid',
 'candy',
 'cao',
 'cap',
 'capabl',
 'capit',
 'capital',
 'capsul',
 'captain',
 'captiv',
 'captur',
 'car',
 'card',
 'cards',
 'care',
 'career',
 'carefre',
 'cargo',
 'carri',
 'carrier',
 'cars',
 'cart',
 'cartoon',
 'carv',
 'case',
 'cases',
 'cast',
 'castl',
 'castle',
 'cat',
 'catalog',
 'catastroph',
 'catch',
 'cats',
 'caught',
 'caus',
 'cause',
 'cave',
 'ccord',
 'cd',
 'celebr',
 'celesti',
 'cell',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceremoni',
 'ceremony',
 'certain',
 'certainli',
 'cg',
 'cgi',
 'chain',
 'chairman',
 'challeng',
 'challenge',
 'challenges',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'char',
 'charact',
 'character',
 'characters',
 'charat',
 'charg',
 'charismat',
 'charm',
 'chase',
 'check',
 'cheer',
 'chef',
 'chemic',
 'chen',
 'cherish',
 'cherri',
 'chest',
 'chi',
 'chiaki',
 'chiba',
 'chibi',
 'chicken',
 'chief',
 'chihaya',
 'chihiro',
 'chika',
 'child',
 'childhood',
 'childish',
 'children',
 'china',
 'chines',
 'chip',
 'chise',
 'chitos',
 'chiyo',
 'chizuru',
 'cho',
 'chocol',
 'chocolate',
 'choic',
 'choice',
 'choir',
 'choos',
 'chose',
 'chosen',
 'chou',
 'choujin',
 'christian',
 'christma',
 'christmas',
 'chronicl',
 'chu',
 'church',
 'ciel',
 'cinderella',
 'cinema',
 'circl',
 'circu',
 'circumst',
 'circumstances',
 'circus',
 'citi',
 'cities',
 'citizen',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'clad',
 'claim',
 'clan',
 'clash',
 'class',
 'classes',
 'classic',
 'classmat',
 'classmate',
 'classmates',
 'classroom',
 'claw',
 'clay',
 'clean',
 'clear',
 'click',
 'client',
 'clients',
 'climax',
 'climb',
 'clip',
 'clock',
 'clone',
 'close',
 'closer',
 'closest',
 'cloth',
 'cloud',
 'clouds',
 'clover',
 'club',
 'clue',
 'clueless',
 'clumsi',
 'cluster',
 'clutch',
 'cm',
 'coach',
 'coast',
 'cocoa',
 'cocotama',
 'code',
 'coexist',
 'cold',
 'collabor',
 'collaps',
 'colleagu',
 'collect',
 'collection',
 'colleg',
 'college',
 'collid',
 'colon',
 'coloni',
 'colonies',
 'color',
 'com',
 'coma',
 'combat',
 'combin',
 'come',
 'comed',
 'comedi',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'command',
 'commemor',
 'comment',
 'commerci',
 'commercials',
 'commiss',
 'commit',
 'common',
 'commonli',
 'commun',
 'community',
 'compani',
 'companion',
 'companions',
 'company',
 'compar',
 'compet',
 'competit',
 'competition',
 'compil',
 'complet',
 'complex',
 'complic',
 'complicated',
 'compos',
 'compris',
 'comput',
 'computer',
 'comrad',
 'comrades',
 'conan',
 'conceal',
 'concept',
 'concern',
 'concert',
 'conclud',
 'conclus',
 'condit',
 'condition',
 'conduct',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'confusion',
 'connect',
 'conquer',
 'conquest',
 'conscious',
 'consciousness',
 'consequ',
 'consid',
 'consider',
 'consist',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consult',
 'consum',
 'contact',
 'contain',
 'contend',
 'content',
 'contest',
 'contin',
 'continent',
 'continu',
 'continues',
 'contract',
 'contrast',
 'contribut',
 'control',
 'conveni',
 'convent',
 'convers',
 'convert',
 'convey',
 'convict',
 'convinc',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'copi',
 'core',
 'corner',
 'corp',
 'corpor',
 'corporation',
 'corps',
 'correct',
 'corrupt',
 'cosmic',
 'cosmo',
 'cosplay',
 'cost',
 'costs',
 'costum',
 'couldn',
 'council',
 'count',
 'counter',
 'countless',
 'countri',
 'countries',
 'country',
 'countrysid',
 'countryside',
 'coup',
 'coupl',
 'couple',
 'courag',
 'courage',
 'cours',
 'course',
 'court',
 'cousin',
 'cov',
 'cover',
 'covet',
 'cow',
 'crab',
 'crack',
 'craft',
 'crane',
 ...]

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.25092632, 0.20290092, ..., 0.03115885, 0.1609036 ,
        0.12787321],
       [0.25092632, 1.        , 0.11891287, ..., 0.03834825, 0.        ,
        0.11803342],
       [0.20290092, 0.11891287, 1.        , ..., 0.        , 0.08006408,
        0.01590712],
       ...,
       [0.03115885, 0.03834825, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.1609036 , 0.        , 0.08006408, ..., 0.        , 1.        ,
        0.06622662],
       [0.12787321, 0.11803342, 0.01590712, ..., 0.        , 0.06622662,
        1.        ]])

In [39]:
similarity.shape

(16107, 16107)

In [40]:
new_df[new_df['Name'] == 'Trigun'].index[0]

2

In [41]:
sorted(list(enumerate(similarity[0])), reverse = True,key =lambda x :x[1])[1:6]

[(3149, 0.3622642035823962),
 (1145, 0.33056760759874076),
 (365, 0.31726990745224676),
 (2312, 0.313529856431228),
 (4028, 0.30582267425849063)]

In [42]:
def recommend(anime):
    x = new_df[new_df['Name'] == anime].index[0]
    distances = similarity[x]
    anime_list = sorted(list(enumerate(distances)), reverse = True,key =lambda x :x[1])[1:11]
    for i in anime_list:
        print(new_df.iloc[i[0]].Name)

In [43]:
new_df[new_df['MAL_ID'] == 178]

     MAL_ID          Name                                               tags
155     178  Ultra Maniac  comedi magic romanc school shoujo t v fantasi ...

In [44]:
recommend('One Piece')

One Piece: Episode of East Blue - Luffy to 4-nin no Nakama no Daibouken
One Piece Film: Strong World
Kaizoku Ouji
One Piece: Oounabara ni Hirake! Dekkai Dekkai Chichi no Yume!
Hazedon
Magi: Sinbad no Bouken (TV)
Kami no Tou
Kushimitama Samurai
Magi: The Labyrinth of Magic
Cike Wu Liuqi

In [45]:
new_df = new_df.merge(anime_images[['MAL_ID','image_url']])

In [51]:
new_df[new_df['MAL_ID'] == 178].image_url

155    https://myanimelist.cdn-dena.com/images/anime/...
Name: image_url, dtype: object

In [46]:
import pickle

In [47]:
pickle.dump(new_df.to_dict(),open('anime.pkl','wb'))

In [48]:
pickle.dump(similarity,open('similarity.pkl','wb'))